<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Página em Construção | APK Tecnologia</title>
    <link href='<?php echo BASE_IMAGES_URL ?>/icon.png' rel='shortcut' type='image/x-icon' />
    <link href='<?php echo BASE_IMAGES_URL ?>/icon.png' rel='icon' type='image/png' />
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_CSS_URL ?>/style.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_CSS_URL ?>/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_CSS_URL ?>/bootstrap-theme.css">
    <script type="text/javascript" src="<?php echo BASE_JS_URL ?>/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo BASE_JS_URL ?>/bootstrap.js"></script>
    <script type="text/javascript" src="<?php echo BASE_JS_URL ?>/index.js"></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="container">
        <div class="centralize">
          <div class="col-md-12 logo_empresa"><img src="<?php echo BASE_IMAGES_URL .'/logotipo.png' ?>" alt="APK Tecnologia" class="img-responsive"></div>
        </div>
        <div class="centralize">
          <h1 class="titulo_construcao">Página em atualização</h1>
          <p class="sub_construcao">em breve novidades.</p>
        </div>
        <div class="centralize">
          <div class="col-md-12 img_construir"><img src="<?php echo BASE_IMAGES_URL ?>/construcao.png" alt="Construção" class="img-responsive"></div>
        </div>
        <ul class="roda_construcao">
          <li class="fLeft campos_contato">
            <p class="titulo_bloco">Entre Em Contato</p>
            <p class="sub_bloco">Via E-mail</p>
            <p class="email_contato"><?php echo SITE_EMAIL ?></p>
          </li>
          <li class="fLeft campos_newsllter">
            <p class="titulo_bloco">Newsletter</p>
            <p class="sub_bloco">Cadastre-se e Receba Nossas Novidades</p>
            <form name="form_news">
              <input type="text" id="nome_news" placeholder="Nome Completo" class="campo_news" />
              <br />
              <input type="text" name="email" id="email_news" placeholder="E-mail" class="campo_news" />
              <br />
              <input type="button" id="btn_news" value="Cadastrar" class="btn_news" />
            </form>
          </li>
        </ul>
      </div>
    </div>
  </body>
</html>
