        </div>
      </div>
    </div>
  </div>
  <div id="footer_container">
    <footer>
      <div class="container-fluid back_footer">
        <div class="container">
          <div class="col-lg-4">
            <h2 class="titulo back_quem_somos">Quem Somos</h2>
            <div class="texto_content">Site voltado a ajudar pessoas que tenham perdidos seus cachorros e a ajudar ONGs necessitadas para melhor atender os Amigo-Bichos</div>
          </div>
          <div class="col-lg-4">
            <h2 class="titulo back_contatos">Contatos</h2>
            <div class="texto_content">Telefone: (16)3333-3333<br />Celular: (16)3333-3333</div>
          </div>
          <div class="col-lg-4">
            <h2 class="titulo back_faleconoco">Fale Conosco</h2>
            <div class="texto_content">Você tem alguma dúvida? Entre em contato através do nosso email: amigo-bicho@gmail.com </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <div id="jquery-ui"></div>
</body>
</html>